# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1197, 728)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(24)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("/* General Application Background */\n"
"QWidget {\n"
"    background-color: #d0e8f2; /* Cool light blue for a calming background */\n"
"    font-family: \'Comic Sans MS\', \'Arial\', sans-serif; /* Kid-friendly font */\n"
"    color: #1a3c6e; /* Dark blue for text */\n"
"}\n"
"\n"
"/* Line Edit Styles */\n"
"QLineEdit {\n"
"    background-color: #ffffff; /* White for clear input visibility */\n"
"    border: 2px solid #4682b4; /* Medium blue border */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    font-size: 16px;\n"
"    color: #1a3c6e; /* Dark blue for text */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #1a3c6e; /* Highlight border with dark blue on focus */\n"
"    background-color: #f0faff; /* Very light blue when focused */\n"
"}\n"
"\n"
"/* Button Styles */\n"
"QPushButton {\n"
"    background-color: #4682b4; /* Medium blue */\n"
"    color: white;\n"
"    border: 2px solid #1a3c6e; /* Dark blue border */\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QPushButton#pushButton_16 {\n"
"    background-color: #4682b4; /* Medium blue */\n"
"    color: white;\n"
"    border:none;\n"
"    font-size: 48px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5a9bd6; /* Lighter blue on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1a3c6e; /* Dark blue when pressed */\n"
"    border: 2px solid #ffffff; /* White border when pressed */\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size: 22px;\n"
"    color: #1a3c6e; /* Dark blue for better visibility */\n"
"    padding: 5px;\n"
"    border: none; /* Ensure labels have no borders */\n"
"}\n"
"\n"
"QLabel#label {\n"
"    font-size: 35px;\n"
"    color: #1a3c6e; /* Dark blue for better visibility */\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel#label_2 {\n"
"    font-size: 35px;\n"
"    color: #1a3c6e; /* Dark blue for better visibility */\n"
"    padding: 5px;\n"
"}\n"
"\n"
"/* Frames and Group Boxes */\n"
"QFrame, QGroupBox {\n"
"    border: 2px solid #4682b4; /* Medium blue border */\n"
"    border-radius: 10px;\n"
"    background-color: #f0faff; /* Very light blue background */\n"
"    padding: 10px;\n"
"}\n"
"\n"
"/* Frames and Group Boxes */\n"
"QFrame#frame_6{\n"
"    border: 2px solid #4682b4; /* Medium blue border */\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"/* CheckBox and RadioButton Styles */\n"
"QCheckBox, QRadioButton {\n"
"    font-size: 16px;\n"
"    color: #1a3c6e; /* Dark blue */\n"
"}\n"
"\n"
"QCheckBox::indicator:checked, QRadioButton::indicator:checked {\n"
"    background-color: #4682b4; /* Medium blue check indicator */\n"
"    border: 1px solid #1a3c6e;\n"
"}\n"
"\n"
"/* Slider Styles */\n"
"QSlider::groove:horizontal, QSlider::groove:vertical {\n"
"    background-color: #4682b4; /* Medium blue groove */\n"
"    height: 8px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal, QSlider::handle:vertical {\n"
"    background: #1a3c6e; /* Dark blue handle */\n"
"    border: 2px solid #ffffff;\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    margin: -5px 0; /* Center the handle */\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QSlider::handle:hover {\n"
"    background: #5a9bd6; /* Lighter blue handle on hover */\n"
"}\n"
"\n"
"QScrollBar:vertical, QScrollBar:horizontal {\n"
"    background-color: #d0e8f2; /* Cool light blue for scrollbar background */\n"
"    border: none;\n"
"    width: 12px;\n"
"}\n"
"\n"
"QScrollBar::handle {\n"
"    background: #4682b4; /* Medium blue for scrollbar handle */\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:hover {\n"
"    background: #5a9bd6; /* Lighter blue on hover */\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: #ffffff; /* White background for clarity */\n"
"    border: 2px solid #4682b4; /* Medium blue border */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    font-size: 16px;\n"
"    color: #1a3c6e; /* Dark blue text */\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 2px solid #1a3c6e; /* Dark blue border on hover */\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 2px solid #5a9bd6; /* Highlighted lighter blue border */\n"
"    background-color: #f0faff; /* Very light blue when focused */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none; /* Removes extra border for the drop-down button */\n"
"    background-color: #4682b4; /* Medium blue for the button */\n"
"    width: 30px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icons/assets/icons/down-arrow.png);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #ffffff; /* White background for drop-down list */\n"
"    border: 2px solid #4682b4; /* Medium blue border for list */\n"
"    color: #1a3c6e; /* Dark blue text for items */\n"
"    selection-background-color: #5a9bd6; /* Lighter blue for selected item */\n"
"    selection-color: #ffffff; /* White text for selected item */\n"
"}\n"
"\n"
"/* TextEdit Styles */\n"
"QTextEdit {\n"
"    background-color: #ffffff; /* White for a clean and clear input area */\n"
"    border: 2px solid #4682b4; /* Medium blue border */\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    font-size: 16px;\n"
"    color: #1a3c6e; /* Dark blue text */\n"
"    font-family: \'Comic Sans MS\', \'Arial\', sans-serif; /* Kid-friendly font */\n"
"}\n"
"\n"
"QTextEdit:focus {\n"
"    border: 2px solid #1a3c6e; /* Highlight border with dark blue on focus */\n"
"    background-color: #f0faff; /* Very light blue background when focused */\n"
"}\n"
"\n"
"/* Scrollbar Styling for QTextEdit */\n"
"QTextEdit QScrollBar:vertical, QTextEdit QScrollBar:horizontal {\n"
"    background-color: #d0e8f2; /* Light blue scrollbar background */\n"
"    border: none;\n"
"    width: 12px;\n"
"}\n"
"\n"
"QTextEdit QScrollBar::handle {\n"
"    background: #4682b4; /* Medium blue for scrollbar handle */\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QTextEdit QScrollBar::handle:hover {\n"
"    background: #5a9bd6; /* Lighter blue handle on hover */\n"
"}\n"
"\n"
"QTextEdit QScrollBar::add-line, QTextEdit QScrollBar::sub-line {\n"
"    background: #4682b4; /* Medium blue for arrow buttons */\n"
"    border: none;\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"QTextEdit QScrollBar::add-line:hover, QTextEdit QScrollBar::sub-line:hover {\n"
"    background: #5a9bd6; /* Lighter blue on hover */\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.page_3)
        self.stackedWidget.setStyleSheet("/* Table Widget Styles */\n"
"QTableWidget {\n"
"    background-color: #ffffff; /* White background for table cells */\n"
"    border: 2px solid #4682b4; /* Medium blue border around the table */\n"
"    border-radius: 5px;\n"
"    gridline-color: #4682b4; /* Medium blue grid lines */\n"
"    font-size: 16px;\n"
"    color: #1a3c6e; /* Dark blue text for cells */\n"
"    font-family: \'Comic Sans MS\', \'Arial\', sans-serif; /* Kid-friendly font */\n"
"}\n"
"\n"
"/* Header Styles */\n"
"QHeaderView::section {\n"
"    background-color: #4682b4; /* Medium blue background for headers */\n"
"    color: #ffffff; /* White text for contrast */\n"
"    font-size: 18px; /* Larger font size for better visibility */\n"
"    font-weight: bold; /* Bold text for emphasis */\n"
"    border: 1px solid #1a3c6e; /* Dark blue border for sections */\n"
"    padding: 8px; /* Increased padding for more space */\n"
"    text-align: center; /* Center-align text in headers */\n"
"    height: 30px; /* Increase header height for better readability */\n"
"}\n"
"\n"
"/* Fix for Horizontal Header Stretch */\n"
"QHeaderView::section:horizontal {\n"
"    min-width: 100px; /* Minimum width for each column header */\n"
"}\n"
"\n"
"/* Fix for Vertical Header (Index Column) */\n"
"QHeaderView::section:vertical {\n"
"    background-color: #f0faff; /* Light blue for index column */\n"
"    font-weight: bold; /* Bold text for better visibility */\n"
"    font-size: 16px; /* Match the cell font size */\n"
"    color: #1a3c6e; /* Dark blue text */\n"
"    padding: 5px; /* Padding for clearer visibility */\n"
"}\n"
"\n"
"/* Table Item Styling */\n"
"QTableWidget::item {\n"
"    padding: 5px; /* Add padding for table cells */\n"
"    text-align: left; /* Align text to the left for readability */\n"
"}\n"
"\n"
"/* Selected Cell Styling */\n"
"QTableWidget::item:selected {\n"
"    background-color: #5a9bd6; /* Lighter blue for selected cell */\n"
"    color: #ffffff; /* White text for better contrast */\n"
"}\n"
"\n"
"/* Scrollbar Styling */\n"
"QTableWidget QScrollBar:vertical, QTableWidget QScrollBar:horizontal {\n"
"    background-color: #d0e8f2; /* Light blue scrollbar background */\n"
"    border: none;\n"
"    width: 12px;\n"
"}\n"
"\n"
"QTableWidget QScrollBar::handle {\n"
"    background: #4682b4; /* Medium blue for scrollbar handle */\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QTableWidget QScrollBar::handle:hover {\n"
"    background: #5a9bd6; /* Lighter blue handle on hover */\n"
"}\n"
"\n"
"QTableWidget QScrollBar::add-line, QTableWidget QScrollBar::sub-line {\n"
"    background: #4682b4; /* Medium blue for arrow buttons */\n"
"    border: none;\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"QTableWidget QScrollBar::add-line:hover, QTableWidget QScrollBar::sub-line:hover {\n"
"    background: #5a9bd6; /* Lighter blue on hover */\n"
"}\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.frame_3 = QtWidgets.QFrame(self.page)
        self.frame_3.setMinimumSize(QtCore.QSize(650, 0))
        self.frame_3.setStyleSheet("QLabel{\n"
"    border:none;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.pushButton_18 = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_18.sizePolicy().hasHeightForWidth())
        self.pushButton_18.setSizePolicy(sizePolicy)
        self.pushButton_18.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_18.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(-1)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_15.addWidget(self.pushButton_18, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_15.addWidget(self.label_13, 1, 2, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_15.addWidget(self.lineEdit_5, 1, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_15.addWidget(self.label_14, 2, 2, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.frame_3)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_15.addWidget(self.comboBox, 2, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_3)
        self.label_15.setObjectName("label_15")
        self.gridLayout_15.addWidget(self.label_15, 3, 2, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_15.addWidget(self.lineEdit_9, 3, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frame_3)
        self.label_20.setObjectName("label_20")
        self.gridLayout_15.addWidget(self.label_20, 4, 2, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_15.addWidget(self.lineEdit_6, 4, 3, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_15.addWidget(self.pushButton_17, 5, 0, 1, 2)
        self.label_16 = QtWidgets.QLabel(self.frame_3)
        self.label_16.setObjectName("label_16")
        self.gridLayout_15.addWidget(self.label_16, 6, 0, 1, 2)
        self.textEdit = QtWidgets.QTextEdit(self.frame_3)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_15.addWidget(self.textEdit, 7, 0, 1, 4)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_15.addWidget(self.pushButton_7, 8, 3, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(300, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(500, 16777215))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 276, 194))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setSpacing(0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setScaledContents(True)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_16.addWidget(self.label_12, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_15.addWidget(self.scrollArea, 1, 0, 4, 2)
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_15.addWidget(self.label_9, 0, 1, 1, 3)
        self.gridLayout_14.addWidget(self.frame_3, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem1, 0, 2, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.page_8)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.frame_8 = QtWidgets.QFrame(self.page_8)
        self.frame_8.setStyleSheet("QLabel{\n"
"    border:none;\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.label_29 = QtWidgets.QLabel(self.frame_8)
        self.label_29.setObjectName("label_29")
        self.gridLayout_21.addWidget(self.label_29, 1, 0, 1, 2)
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_21.addWidget(self.pushButton_13, 3, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.frame_8)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_21.addWidget(self.label_24, 0, 0, 1, 2)
        self.tableWidget_3 = QtWidgets.QTableWidget(self.frame_8)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(3)
        self.tableWidget_3.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(2, 2, item)
        self.tableWidget_3.horizontalHeader().setVisible(False)
        self.tableWidget_3.horizontalHeader().setMinimumSectionSize(136)
        self.tableWidget_3.verticalHeader().setVisible(False)
        self.gridLayout_21.addWidget(self.tableWidget_3, 2, 0, 1, 2)
        self.gridLayout_19.addWidget(self.frame_8, 0, 3, 1, 1)
        self.frame_13 = QtWidgets.QFrame(self.page_8)
        self.frame_13.setStyleSheet("QLabel{\n"
"    border:none;\n"
"}")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.label_25 = QtWidgets.QLabel(self.frame_13)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_22.addWidget(self.label_25, 0, 0, 1, 2)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_13)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_22.addWidget(self.lineEdit_12, 2, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.frame_13)
        self.label_30.setObjectName("label_30")
        self.gridLayout_22.addWidget(self.label_30, 2, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.frame_13)
        self.label_28.setObjectName("label_28")
        self.gridLayout_22.addWidget(self.label_28, 1, 0, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_13)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_22.addWidget(self.lineEdit_11, 1, 1, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_22.addWidget(self.pushButton_14, 3, 1, 1, 1)
        self.gridLayout_19.addWidget(self.frame_13, 1, 3, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.page_8)
        self.frame_5.setMaximumSize(QtCore.QSize(613, 16777215))
        self.frame_5.setStyleSheet("QLabel{\n"
"    border:none;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_2.sizePolicy().hasHeightForWidth())
        self.tableWidget_2.setSizePolicy(sizePolicy)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(5, 3, item)
        self.tableWidget_2.horizontalHeader().setVisible(False)
        self.tableWidget_2.horizontalHeader().setMinimumSectionSize(126)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.gridLayout_23.addWidget(self.tableWidget_2, 3, 1, 1, 2)
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_23.addWidget(self.pushButton_12, 4, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.frame_5)
        self.label_27.setObjectName("label_27")
        self.gridLayout_23.addWidget(self.label_27, 1, 1, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_23.addWidget(self.lineEdit_10, 1, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.frame_5)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_23.addWidget(self.label_23, 0, 1, 1, 2)
        self.label_26 = QtWidgets.QLabel(self.frame_5)
        self.label_26.setStyleSheet("QLabel#label_26{\n"
"    font-family: \'Comic Sans MS\', \'Arial\', sans-serif;\n"
"    font: 75 14pt;\n"
"}")
        self.label_26.setObjectName("label_26")
        self.gridLayout_23.addWidget(self.label_26, 2, 1, 1, 2)
        self.gridLayout_19.addWidget(self.frame_5, 0, 1, 2, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem2, 0, 4, 2, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem3, 0, 0, 2, 1)
        self.stackedWidget.addWidget(self.page_8)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.page_7)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.frame_4 = QtWidgets.QFrame(self.page_7)
        self.frame_4.setStyleSheet("QLabel{\n"
"    border:none;\n"
"}\n"
"\n"
"QLabel#label_22{\n"
"    border: 2px solid rgb(70, 130, 180);\n"
"}\n"
"\n"
"/* Table Widget Styles */\n"
"QTableWidget {\n"
"    background-color: #ffffff; /* White background for table cells */\n"
"    border: 2px solid #4682b4; /* Medium blue border around the table */\n"
"    border-radius: 5px;\n"
"    gridline-color: #4682b4; /* Medium blue grid lines */\n"
"    font-size: 16px;\n"
"    color: #1a3c6e; /* Dark blue text for cells */\n"
"    font-family: \'Comic Sans MS\', \'Arial\', sans-serif; /* Kid-friendly font */\n"
"}\n"
"\n"
"/* Header Styles */\n"
"QHeaderView::section {\n"
"    background-color: #4682b4; /* Medium blue background for headers */\n"
"    color: #ffffff; /* White text for contrast */\n"
"    font-size: 18px; /* Larger font size for better visibility */\n"
"    font-weight: bold; /* Bold text for emphasis */\n"
"    border: 1px solid #1a3c6e; /* Dark blue border for sections */\n"
"    padding: 8px; /* Increased padding for more space */\n"
"    text-align: center; /* Center-align text in headers */\n"
"    height: 30px; /* Increase header height for better readability */\n"
"}\n"
"\n"
"/* Fix for Horizontal Header Stretch */\n"
"QHeaderView::section:horizontal {\n"
"    min-width: 100px; /* Minimum width for each column header */\n"
"}\n"
"\n"
"/* Fix for Vertical Header (Index Column) */\n"
"QHeaderView::section:vertical {\n"
"    background-color: #f0faff; /* Light blue for index column */\n"
"    font-weight: bold; /* Bold text for better visibility */\n"
"    font-size: 16px; /* Match the cell font size */\n"
"    color: #1a3c6e; /* Dark blue text */\n"
"    padding: 5px; /* Padding for clearer visibility */\n"
"}\n"
"\n"
"/* Table Item Styling */\n"
"QTableWidget::item {\n"
"    padding: 5px; /* Add padding for table cells */\n"
"    text-align: left; /* Align text to the left for readability */\n"
"}\n"
"\n"
"/* Selected Cell Styling */\n"
"QTableWidget::item:selected {\n"
"    background-color: #5a9bd6; /* Lighter blue for selected cell */\n"
"    color: #ffffff; /* White text for better contrast */\n"
"}\n"
"\n"
"/* Scrollbar Styling */\n"
"QTableWidget QScrollBar:vertical, QTableWidget QScrollBar:horizontal {\n"
"    background-color: #d0e8f2; /* Light blue scrollbar background */\n"
"    border: none;\n"
"    width: 12px;\n"
"}\n"
"\n"
"QTableWidget QScrollBar::handle {\n"
"    background: #4682b4; /* Medium blue for scrollbar handle */\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QTableWidget QScrollBar::handle:hover {\n"
"    background: #5a9bd6; /* Lighter blue handle on hover */\n"
"}\n"
"\n"
"QTableWidget QScrollBar::add-line, QTableWidget QScrollBar::sub-line {\n"
"    background: #4682b4; /* Medium blue for arrow buttons */\n"
"    border: none;\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"QTableWidget QScrollBar::add-line:hover, QTableWidget QScrollBar::sub-line:hover {\n"
"    background: #5a9bd6; /* Lighter blue on hover */\n"
"}\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_8.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout.addWidget(self.pushButton_8)
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_11.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout.addWidget(self.pushButton_11)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_10.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout.addWidget(self.pushButton_10)
        self.gridLayout_18.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.frame_4)
        self.tableWidget.setMinimumSize(QtCore.QSize(773, 0))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 5, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(152)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.gridLayout_18.addWidget(self.tableWidget, 2, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.frame_4)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_18.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.frame_4)
        self.label_22.setObjectName("label_22")
        self.gridLayout_18.addWidget(self.label_22, 1, 0, 1, 1)
        self.gridLayout_17.addWidget(self.frame_4, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem5, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem6, 0, 2, 1, 1)
        self.stackedWidget.addWidget(self.page_7)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem7, 0, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem8, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.page_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_5.setSpacing(50)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setMaximumSize(QtCore.QSize(100, 100))
        self.label_4.setStyleSheet("border:none")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/icons/assets/icons/add_10115285-removebg-preview (1).png"))
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_9.addWidget(self.label_4, 0, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_3.setIconSize(QtCore.QSize(46, 65))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_9.addWidget(self.pushButton_3, 1, 0, 1, 3)
        self.gridLayout_5.addLayout(self.gridLayout_9, 1, 0, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setMaximumSize(QtCore.QSize(100, 100))
        self.label_5.setStyleSheet("border:none;")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/icons/assets/icons/box_5317283-removebg-preview.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_10.addWidget(self.label_5, 0, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_10.addWidget(self.pushButton_4, 1, 0, 1, 3)
        self.gridLayout_5.addLayout(self.gridLayout_10, 1, 1, 1, 1)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setMaximumSize(QtCore.QSize(100, 100))
        self.label_6.setStyleSheet("border:none;")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/icons/assets/icons/shopping_5566654-removebg-preview.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_11.addWidget(self.label_6, 0, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_5.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_11.addWidget(self.pushButton_5, 1, 0, 1, 3)
        self.gridLayout_5.addLayout(self.gridLayout_11, 2, 0, 1, 1)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setMaximumSize(QtCore.QSize(100, 100))
        self.label_7.setStyleSheet("border:none;")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/icons/assets/icons/analytics_796128-removebg-preview.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_12.addWidget(self.label_7, 0, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_6.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_12.addWidget(self.pushButton_6, 1, 0, 1, 3)
        self.gridLayout_5.addLayout(self.gridLayout_12, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setStyleSheet("border:none;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 0, 0, 1, 2)
        self.gridLayout_6.addWidget(self.frame_2, 1, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem9, 1, 2, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem10, 2, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout_2.addWidget(self.stackedWidget, 1, 0, 1, 1)
        self.stackedWidget_2.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem11, 4, 0, 1, 3)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem12, 1, 0, 1, 3)
        self.stackedWidget_3 = QtWidgets.QStackedWidget(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget_3.sizePolicy().hasHeightForWidth())
        self.stackedWidget_3.setSizePolicy(sizePolicy)
        self.stackedWidget_3.setMinimumSize(QtCore.QSize(500, 0))
        self.stackedWidget_3.setStyleSheet("QStackedWidget{\n"
"    border:none;\n"
"    background:none;\n"
"    background-color: rgb(240, 250, 255);\n"
"}\n"
"\n"
"QFrame{\n"
"    padding:0px;\n"
"}")
        self.stackedWidget_3.setObjectName("stackedWidget_3")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem13, 2, 0, 1, 2)
        self.frame = QtWidgets.QFrame(self.page_5)
        self.frame.setMinimumSize(QtCore.QSize(0, 71))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(-1)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border:none;background:transparent;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 2)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 4, 1, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setStyleSheet("padding:0px;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setStyleSheet("padding:5px;border:none;")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_4.addWidget(self.lineEdit_2)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_9.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_9.setStyleSheet("padding:0px;\n"
"border:none;\n"
"background:none;")
        self.pushButton_9.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/assets/icons/password/eye-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon)
        self.pushButton_9.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_4.addWidget(self.pushButton_9)
        self.gridLayout_3.addWidget(self.frame_6, 3, 0, 1, 2)
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 2, 0, 1, 2)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 4, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame, 1, 0, 1, 2)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem14, 0, 0, 1, 2)
        self.stackedWidget_3.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page_6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.frame_7 = QtWidgets.QFrame(self.page_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.pushButton_16 = QtWidgets.QPushButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_16.sizePolicy().hasHeightForWidth())
        self.pushButton_16.setSizePolicy(sizePolicy)
        self.pushButton_16.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_16.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(-1)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_13.addWidget(self.pushButton_16, 0, 1, 1, 1)
        self.frame_10 = QtWidgets.QFrame(self.frame_7)
        self.frame_10.setStyleSheet("QFrame{\n"
"    border: none;\n"
"}\n"
"\n"
"QLabel{\n"
"    border:none;\n"
"}\n"
"\n"
"QFrame#frame_11{\n"
"     border: 2px solid #4682b4;\n"
"\n"
"}\n"
"\n"
"QLineEdit#lineEdit_7{\n"
"    border:none;\n"
"}\n"
"\n"
"")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.label_17 = QtWidgets.QLabel(self.frame_10)
        self.label_17.setStyleSheet("border:none;")
        self.label_17.setObjectName("label_17")
        self.gridLayout_20.addWidget(self.label_17, 1, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_10)
        self.label_18.setObjectName("label_18")
        self.gridLayout_20.addWidget(self.label_18, 3, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_10)
        self.label_11.setStyleSheet("border:none;")
        self.label_11.setObjectName("label_11")
        self.gridLayout_20.addWidget(self.label_11, 0, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_20.addWidget(self.lineEdit_3, 0, 1, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_20.addWidget(self.lineEdit_4, 1, 1, 1, 1)
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 39))
        self.frame_11.setStyleSheet("padding:0px;")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_7.sizePolicy().hasHeightForWidth())
        self.lineEdit_7.setSizePolicy(sizePolicy)
        self.lineEdit_7.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_6.addWidget(self.lineEdit_7)
        self.pushButton_20 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_20.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_20.setStyleSheet("padding:0px;\n"
"border:none;\n"
"background:none;")
        self.pushButton_20.setText("")
        self.pushButton_20.setIcon(icon)
        self.pushButton_20.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_6.addWidget(self.pushButton_20)
        self.gridLayout_20.addWidget(self.frame_11, 3, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_10)
        self.label_19.setObjectName("label_19")
        self.gridLayout_20.addWidget(self.label_19, 4, 0, 1, 1)
        self.frame_12 = QtWidgets.QFrame(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setMinimumSize(QtCore.QSize(0, 39))
        self.frame_12.setStyleSheet("padding:0px;\n"
"border:2px solid rgb(70, 130, 180);")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_8.sizePolicy().hasHeightForWidth())
        self.lineEdit_8.setSizePolicy(sizePolicy)
        self.lineEdit_8.setStyleSheet("border:none")
        self.lineEdit_8.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_7.addWidget(self.lineEdit_8)
        self.pushButton_21 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_21.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_21.setStyleSheet("padding:0px;\n"
"border:none;\n"
"background:none;")
        self.pushButton_21.setText("")
        self.pushButton_21.setIcon(icon)
        self.pushButton_21.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_21.setObjectName("pushButton_21")
        self.horizontalLayout_7.addWidget(self.pushButton_21)
        self.gridLayout_20.addWidget(self.frame_12, 4, 1, 1, 1)
        self.gridLayout_13.addWidget(self.frame_10, 1, 1, 2, 4)
        self.pushButton_15 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_13.addWidget(self.pushButton_15, 3, 4, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setStyleSheet("border:none;")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_13.addWidget(self.label_10, 0, 2, 1, 3)
        self.gridLayout_8.addWidget(self.frame_7, 0, 0, 1, 1)
        self.stackedWidget_3.addWidget(self.page_6)
        self.gridLayout_4.addWidget(self.stackedWidget_3, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 3)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem15, 3, 0, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem16, 2, 2, 2, 1)
        self.stackedWidget_2.addWidget(self.page_4)
        self.gridLayout.addWidget(self.stackedWidget_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget_2.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_3.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Faiz e Hussaini Traders"))
        self.pushButton_18.setText(_translate("MainWindow", "<"))
        self.label_13.setText(_translate("MainWindow", "Name"))
        self.label_14.setText(_translate("MainWindow", "Category"))
        self.comboBox.setItemText(0, _translate("MainWindow", "New Item"))
        self.comboBox.setItemText(1, _translate("MainWindow", "New Item"))
        self.comboBox.setItemText(2, _translate("MainWindow", "New Item"))
        self.comboBox.setItemText(3, _translate("MainWindow", "New Item"))
        self.comboBox.setItemText(4, _translate("MainWindow", "New Item"))
        self.comboBox.setItemText(5, _translate("MainWindow", "New Item"))
        self.label_15.setText(_translate("MainWindow", "Price"))
        self.label_20.setText(_translate("MainWindow", "Quantity"))
        self.pushButton_17.setText(_translate("MainWindow", "Upload Image"))
        self.label_16.setText(_translate("MainWindow", "Description:"))
        self.pushButton_7.setText(_translate("MainWindow", "Add Product"))
        self.label_12.setText(_translate("MainWindow", "Product Picture"))
        self.label_9.setText(_translate("MainWindow", "Add Product"))
        self.label_29.setText(_translate("MainWindow", "Product        Quantity      Price"))
        self.pushButton_13.setText(_translate("MainWindow", "Process Order"))
        self.label_24.setText(_translate("MainWindow", "Sale Info"))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_3.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Column"))
        __sortingEnabled = self.tableWidget_3.isSortingEnabled()
        self.tableWidget_3.setSortingEnabled(False)
        item = self.tableWidget_3.item(0, 0)
        item.setText(_translate("MainWindow", "123"))
        item = self.tableWidget_3.item(0, 2)
        item.setText(_translate("MainWindow", "123"))
        item = self.tableWidget_3.item(1, 0)
        item.setText(_translate("MainWindow", "1231"))
        item = self.tableWidget_3.item(1, 2)
        item.setText(_translate("MainWindow", "3213"))
        item = self.tableWidget_3.item(2, 0)
        item.setText(_translate("MainWindow", "3213"))
        item = self.tableWidget_3.item(2, 2)
        item.setText(_translate("MainWindow", "23131"))
        self.tableWidget_3.setSortingEnabled(__sortingEnabled)
        self.label_25.setText(_translate("MainWindow", "Customer Information"))
        self.label_30.setText(_translate("MainWindow", "Discount:"))
        self.label_28.setText(_translate("MainWindow", "Customer Name:"))
        self.pushButton_14.setText(_translate("MainWindow", "Save Customer Information"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Product ID"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Price"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Quantity"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.item(0, 0)
        item.setText(_translate("MainWindow", "123"))
        item = self.tableWidget_2.item(0, 1)
        item.setText(_translate("MainWindow", "3213"))
        item = self.tableWidget_2.item(0, 2)
        item.setText(_translate("MainWindow", "31232"))
        item = self.tableWidget_2.item(0, 3)
        item.setText(_translate("MainWindow", "312321"))
        item = self.tableWidget_2.item(1, 0)
        item.setText(_translate("MainWindow", "321312"))
        item = self.tableWidget_2.item(1, 1)
        item.setText(_translate("MainWindow", "321312"))
        item = self.tableWidget_2.item(1, 2)
        item.setText(_translate("MainWindow", "32132"))
        item = self.tableWidget_2.item(1, 3)
        item.setText(_translate("MainWindow", "13123"))
        item = self.tableWidget_2.item(2, 0)
        item.setText(_translate("MainWindow", "3123"))
        item = self.tableWidget_2.item(2, 1)
        item.setText(_translate("MainWindow", "12312"))
        item = self.tableWidget_2.item(2, 2)
        item.setText(_translate("MainWindow", "123"))
        item = self.tableWidget_2.item(2, 3)
        item.setText(_translate("MainWindow", "213"))
        item = self.tableWidget_2.item(3, 0)
        item.setText(_translate("MainWindow", "12312"))
        item = self.tableWidget_2.item(3, 1)
        item.setText(_translate("MainWindow", "123"))
        item = self.tableWidget_2.item(3, 2)
        item.setText(_translate("MainWindow", "123"))
        item = self.tableWidget_2.item(3, 3)
        item.setText(_translate("MainWindow", "123"))
        item = self.tableWidget_2.item(4, 0)
        item.setText(_translate("MainWindow", "12"))
        item = self.tableWidget_2.item(4, 1)
        item.setText(_translate("MainWindow", "123"))
        item = self.tableWidget_2.item(4, 2)
        item.setText(_translate("MainWindow", "123"))
        item = self.tableWidget_2.item(4, 3)
        item.setText(_translate("MainWindow", "213"))
        item = self.tableWidget_2.item(5, 0)
        item.setText(_translate("MainWindow", "3123"))
        item = self.tableWidget_2.item(5, 1)
        item.setText(_translate("MainWindow", "123"))
        item = self.tableWidget_2.item(5, 2)
        item.setText(_translate("MainWindow", "213"))
        item = self.tableWidget_2.item(5, 3)
        item.setText(_translate("MainWindow", "123123"))
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.pushButton_12.setText(_translate("MainWindow", "Add Item"))
        self.label_27.setText(_translate("MainWindow", "Search:"))
        self.label_23.setText(_translate("MainWindow", "Find Product"))
        self.label_26.setText(_translate("MainWindow", "Product ID    Name            Price              Quantity In Stock"))
        self.pushButton_8.setText(_translate("MainWindow", "Add New Product"))
        self.pushButton_11.setText(_translate("MainWindow", "Update Product Info"))
        self.pushButton_10.setText(_translate("MainWindow", "Delete Product"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Product ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Quantity "))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Category"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Quantity"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Description"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "zzxz"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "xssx"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "xxxxxxxxxx"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "efwffeafaf"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("MainWindow", "frefserf"))
        item = self.tableWidget.item(1, 3)
        item.setText(_translate("MainWindow", "erfse"))
        item = self.tableWidget.item(1, 5)
        item.setText(_translate("MainWindow", "rfrsef"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "xsssssssssssss"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("MainWindow", "feferf"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("MainWindow", "efrse"))
        item = self.tableWidget.item(2, 3)
        item.setText(_translate("MainWindow", "rsefr"))
        item = self.tableWidget.item(2, 5)
        item.setText(_translate("MainWindow", "r"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "ssssssssssss"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("MainWindow", "efeafer"))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("MainWindow", "frsef"))
        item = self.tableWidget.item(3, 3)
        item.setText(_translate("MainWindow", "serfserg"))
        item = self.tableWidget.item(3, 5)
        item.setText(_translate("MainWindow", "gresgrse"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("MainWindow", "ssssssssss"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("MainWindow", "ferferf"))
        item = self.tableWidget.item(4, 2)
        item.setText(_translate("MainWindow", "sgrs"))
        item = self.tableWidget.item(4, 3)
        item.setText(_translate("MainWindow", "resgre"))
        item = self.tableWidget.item(4, 5)
        item.setText(_translate("MainWindow", "grseg"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("MainWindow", "erfesfersf"))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("MainWindow", "frsefres"))
        item = self.tableWidget.item(5, 2)
        item.setText(_translate("MainWindow", "freegeg"))
        item = self.tableWidget.item(5, 3)
        item.setText(_translate("MainWindow", "ssssssssss"))
        item = self.tableWidget.item(5, 5)
        item.setText(_translate("MainWindow", "g"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_21.setText(_translate("MainWindow", "Products Status"))
        self.label_22.setText(_translate("MainWindow", "Product ID     Name             Category         Price               Quantity        Description"))
        self.pushButton_3.setText(_translate("MainWindow", "Add Product"))
        self.pushButton_4.setText(_translate("MainWindow", "View Products"))
        self.pushButton_5.setText(_translate("MainWindow", "Sell Products"))
        self.pushButton_6.setText(_translate("MainWindow", "Generate Report"))
        self.label_8.setText(_translate("MainWindow", "Menu"))
        self.label_3.setText(_translate("MainWindow", "Login"))
        self.pushButton.setText(_translate("MainWindow", "Register"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Password"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Email"))
        self.pushButton_2.setText(_translate("MainWindow", "Login"))
        self.pushButton_16.setText(_translate("MainWindow", "<"))
        self.label_17.setText(_translate("MainWindow", "Employee Name:"))
        self.label_18.setText(_translate("MainWindow", "Password:"))
        self.label_11.setText(_translate("MainWindow", "Employee Mail:"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "default@example.com"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Alan etc"))
        self.lineEdit_7.setPlaceholderText(_translate("MainWindow", "Password"))
        self.label_19.setText(_translate("MainWindow", "Confirm Password:"))
        self.lineEdit_8.setPlaceholderText(_translate("MainWindow", "Password"))
        self.pushButton_15.setText(_translate("MainWindow", "Add Employee"))
        self.label_10.setText(_translate("MainWindow", "Add New Employee"))
        self.label_2.setText(_translate("MainWindow", "Faiz e Hussaini Traders"))
import new_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
